package com.ztlt.service;

import com.ztlt.entity.Drecord;
import com.ztlt.entity.DrecordExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface DrecordService {

    //实现分页查询
    List<Drecord> selectByExamplePage(DrecordExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    long countByExample(DrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int deleteByExample(DrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int insert(Drecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int insertSelective(Drecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    List<Drecord> selectByExample(DrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    Drecord selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Drecord record, @Param("example") DrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int updateByExample(@Param("record") Drecord record, @Param("example") DrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int updateByPrimaryKeySelective(Drecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_D_RECORD
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    int updateByPrimaryKey(Drecord record);
}
