package com.ztlt.service;

import com.ztlt.entity.ProjectFile;
import com.ztlt.entity.ProjectFileExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface ProjectFileService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    long countByExample(ProjectFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int deleteByExample(ProjectFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int insert(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int insertSelective(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    List<ProjectFile> selectByExample(ProjectFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    ProjectFile selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProjectFile record, @Param("example") ProjectFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int updateByExample(@Param("record") ProjectFile record, @Param("example") ProjectFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_P_BASIC_FILE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    int updateByPrimaryKey(ProjectFile record);
}
