package com.ztlt.service;

import com.ztlt.entity.Project;
import com.ztlt.entity.ProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectService {

    //实现分页查询
    List<Project> selectByExamplePage(ProjectExample example);

    List<Project> selectByExamplePage2(ProjectExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    long countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int deleteByPrimaryKey(String pNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    Project selectByPrimaryKey(String pNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    int updateByPrimaryKey(Project record);
}
