package com.ztlt.mapper;

import com.ztlt.entity.CheckRecord;
import com.ztlt.entity.CheckRecordExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    long countByExample(CheckRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int deleteByExample(CheckRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int insert(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int insertSelective(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    List<CheckRecord> selectByExample(CheckRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    CheckRecord selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") CheckRecord record, @Param("example") CheckRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int updateByExample(@Param("record") CheckRecord record, @Param("example") CheckRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int updateByPrimaryKeySelective(CheckRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CHECK_RECORD
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    int updateByPrimaryKey(CheckRecord record);
}