package com.ztlt.mapper;

import com.ztlt.entity.ProjectType;
import com.ztlt.entity.ProjectTypeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    long countByExample(ProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int deleteByExample(ProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int insert(ProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int insertSelective(ProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    List<ProjectType> selectByExample(ProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    ProjectType selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProjectType record, @Param("example") ProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int updateByExample(@Param("record") ProjectType record, @Param("example") ProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT_TYPE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    int updateByPrimaryKey(ProjectType record);
}