package com.ztlt.mapper;

import com.ztlt.entity.Sked;
import com.ztlt.entity.SkedExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    long countByExample(SkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int deleteByExample(SkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int insert(Sked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int insertSelective(Sked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    List<Sked> selectByExample(SkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    Sked selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sked record, @Param("example") SkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int updateByExample(@Param("record") Sked record, @Param("example") SkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int updateByPrimaryKeySelective(Sked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    int updateByPrimaryKey(Sked record);
}