package com.ztlt.mapper;

import com.ztlt.entity.Subtask;
import com.ztlt.entity.SubtaskExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    long countByExample(SubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int deleteByExample(SubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int insert(Subtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int insertSelective(Subtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    List<Subtask> selectByExample(SubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    Subtask selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Subtask record, @Param("example") SubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int updateByExample(@Param("record") Subtask record, @Param("example") SubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int updateByPrimaryKeySelective(Subtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUBTASK
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    int updateByPrimaryKey(Subtask record);
}