package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class CheckRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.PC_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private BigDecimal pcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.TP_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private BigDecimal tpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.VALUE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.CR_STATE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private BigDecimal crState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CHECK_RECORD.CR_REMARK
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    private String crRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.ID
     *
     * @return the value of TB_CHECK_RECORD.ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.ID
     *
     * @param id the value for TB_CHECK_RECORD.ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.PC_ID
     *
     * @return the value of TB_CHECK_RECORD.PC_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public BigDecimal getPcId() {
        return pcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.PC_ID
     *
     * @param pcId the value for TB_CHECK_RECORD.PC_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setPcId(BigDecimal pcId) {
        this.pcId = pcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.TP_ID
     *
     * @return the value of TB_CHECK_RECORD.TP_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public BigDecimal getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.TP_ID
     *
     * @param tpId the value for TB_CHECK_RECORD.TP_ID
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setTpId(BigDecimal tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.VALUE
     *
     * @return the value of TB_CHECK_RECORD.VALUE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.VALUE
     *
     * @param value the value for TB_CHECK_RECORD.VALUE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.CR_STATE
     *
     * @return the value of TB_CHECK_RECORD.CR_STATE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public BigDecimal getCrState() {
        return crState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.CR_STATE
     *
     * @param crState the value for TB_CHECK_RECORD.CR_STATE
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setCrState(BigDecimal crState) {
        this.crState = crState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CHECK_RECORD.CR_REMARK
     *
     * @return the value of TB_CHECK_RECORD.CR_REMARK
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public String getCrRemark() {
        return crRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CHECK_RECORD.CR_REMARK
     *
     * @param crRemark the value for TB_CHECK_RECORD.CR_REMARK
     *
     * @mbg.generated Wed Feb 13 09:52:27 CST 2019
     */
    public void setCrRemark(String crRemark) {
        this.crRemark = crRemark == null ? null : crRemark.trim();
    }
}