package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Drecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.R_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private BigDecimal rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.TP_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private BigDecimal tpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.PDR_VALUE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private String pdrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.D_STATE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private BigDecimal dState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_D_RECORD.D_REMARK
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    private String dRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.ID
     *
     * @return the value of TB_PROCESS_D_RECORD.ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.ID
     *
     * @param id the value for TB_PROCESS_D_RECORD.ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.R_ID
     *
     * @return the value of TB_PROCESS_D_RECORD.R_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public BigDecimal getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.R_ID
     *
     * @param rId the value for TB_PROCESS_D_RECORD.R_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setrId(BigDecimal rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.TP_ID
     *
     * @return the value of TB_PROCESS_D_RECORD.TP_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public BigDecimal getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.TP_ID
     *
     * @param tpId the value for TB_PROCESS_D_RECORD.TP_ID
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setTpId(BigDecimal tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.PDR_VALUE
     *
     * @return the value of TB_PROCESS_D_RECORD.PDR_VALUE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public String getPdrValue() {
        return pdrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.PDR_VALUE
     *
     * @param pdrValue the value for TB_PROCESS_D_RECORD.PDR_VALUE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setPdrValue(String pdrValue) {
        this.pdrValue = pdrValue == null ? null : pdrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.D_STATE
     *
     * @return the value of TB_PROCESS_D_RECORD.D_STATE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public BigDecimal getdState() {
        return dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.D_STATE
     *
     * @param dState the value for TB_PROCESS_D_RECORD.D_STATE
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setdState(BigDecimal dState) {
        this.dState = dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_D_RECORD.D_REMARK
     *
     * @return the value of TB_PROCESS_D_RECORD.D_REMARK
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public String getdRemark() {
        return dRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_D_RECORD.D_REMARK
     *
     * @param dRemark the value for TB_PROCESS_D_RECORD.D_REMARK
     *
     * @mbg.generated Mon Jan 28 11:48:20 CST 2019
     */
    public void setdRemark(String dRemark) {
        this.dRemark = dRemark == null ? null : dRemark.trim();
    }

    @Override
    public String toString() {
        return "Drecord{" +
                "id=" + id +
                ", rId=" + rId +
                ", tpId=" + tpId +
                ", pdrValue='" + pdrValue + '\'' +
                ", dState=" + dState +
                ", dRemark='" + dRemark + '\'' +
                '}';
    }
}