package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectExample implements Serializable {

    protected int stratRow;
    protected int endRow;
    protected String name;
    protected String pFType;
    protected String pType;

    public String getpFType() {
        return pFType;
    }

    public void setpFType(String pFType) {
        this.pFType = pFType;
    }

    public String getpType() {
        return pType;
    }

    public void setpType(String pType) {
        this.pType = pType;
    }

    public void setOredCriteria(List<Criteria> oredCriteria) {
        this.oredCriteria = oredCriteria;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStratRow() {
        return stratRow;
    }

    public void setStratRow(int stratRow) {
        this.stratRow = stratRow;
    }

    public int getEndRow() {
        return endRow;
    }

    public void setEndRow(int endRow) {
        this.endRow = endRow;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPNumberIsNull() {
            addCriterion("P_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPNumberIsNotNull() {
            addCriterion("P_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPNumberEqualTo(String value) {
            addCriterion("P_NUMBER =", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberNotEqualTo(String value) {
            addCriterion("P_NUMBER <>", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberGreaterThan(String value) {
            addCriterion("P_NUMBER >", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberGreaterThanOrEqualTo(String value) {
            addCriterion("P_NUMBER >=", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberLessThan(String value) {
            addCriterion("P_NUMBER <", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberLessThanOrEqualTo(String value) {
            addCriterion("P_NUMBER <=", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberLike(String value) {
            addCriterion("P_NUMBER like", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberNotLike(String value) {
            addCriterion("P_NUMBER not like", value, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberIn(List<String> values) {
            addCriterion("P_NUMBER in", values, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberNotIn(List<String> values) {
            addCriterion("P_NUMBER not in", values, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberBetween(String value1, String value2) {
            addCriterion("P_NUMBER between", value1, value2, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNumberNotBetween(String value1, String value2) {
            addCriterion("P_NUMBER not between", value1, value2, "pNumber");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("P_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("P_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("P_NAME =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("P_NAME <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("P_NAME >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("P_NAME >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("P_NAME <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("P_NAME <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("P_NAME like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("P_NAME not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("P_NAME in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("P_NAME not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("P_NAME between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("P_NAME not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNull() {
            addCriterion("P_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNotNull() {
            addCriterion("P_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPTypeEqualTo(BigDecimal value) {
            addCriterion("P_TYPE =", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotEqualTo(BigDecimal value) {
            addCriterion("P_TYPE <>", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThan(BigDecimal value) {
            addCriterion("P_TYPE >", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_TYPE >=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThan(BigDecimal value) {
            addCriterion("P_TYPE <", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_TYPE <=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeIn(List<BigDecimal> values) {
            addCriterion("P_TYPE in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotIn(List<BigDecimal> values) {
            addCriterion("P_TYPE not in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_TYPE between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_TYPE not between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPAddressIsNull() {
            addCriterion("P_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andPAddressIsNotNull() {
            addCriterion("P_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andPAddressEqualTo(String value) {
            addCriterion("P_ADDRESS =", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotEqualTo(String value) {
            addCriterion("P_ADDRESS <>", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressGreaterThan(String value) {
            addCriterion("P_ADDRESS >", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressGreaterThanOrEqualTo(String value) {
            addCriterion("P_ADDRESS >=", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLessThan(String value) {
            addCriterion("P_ADDRESS <", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLessThanOrEqualTo(String value) {
            addCriterion("P_ADDRESS <=", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLike(String value) {
            addCriterion("P_ADDRESS like", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotLike(String value) {
            addCriterion("P_ADDRESS not like", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressIn(List<String> values) {
            addCriterion("P_ADDRESS in", values, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotIn(List<String> values) {
            addCriterion("P_ADDRESS not in", values, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressBetween(String value1, String value2) {
            addCriterion("P_ADDRESS between", value1, value2, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotBetween(String value1, String value2) {
            addCriterion("P_ADDRESS not between", value1, value2, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPSummaryIsNull() {
            addCriterion("P_SUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andPSummaryIsNotNull() {
            addCriterion("P_SUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andPSummaryEqualTo(String value) {
            addCriterion("P_SUMMARY =", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryNotEqualTo(String value) {
            addCriterion("P_SUMMARY <>", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryGreaterThan(String value) {
            addCriterion("P_SUMMARY >", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("P_SUMMARY >=", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryLessThan(String value) {
            addCriterion("P_SUMMARY <", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryLessThanOrEqualTo(String value) {
            addCriterion("P_SUMMARY <=", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryLike(String value) {
            addCriterion("P_SUMMARY like", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryNotLike(String value) {
            addCriterion("P_SUMMARY not like", value, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryIn(List<String> values) {
            addCriterion("P_SUMMARY in", values, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryNotIn(List<String> values) {
            addCriterion("P_SUMMARY not in", values, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryBetween(String value1, String value2) {
            addCriterion("P_SUMMARY between", value1, value2, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPSummaryNotBetween(String value1, String value2) {
            addCriterion("P_SUMMARY not between", value1, value2, "pSummary");
            return (Criteria) this;
        }

        public Criteria andPCaptainIsNull() {
            addCriterion("P_CAPTAIN is null");
            return (Criteria) this;
        }

        public Criteria andPCaptainIsNotNull() {
            addCriterion("P_CAPTAIN is not null");
            return (Criteria) this;
        }

        public Criteria andPCaptainEqualTo(String value) {
            addCriterion("P_CAPTAIN =", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainNotEqualTo(String value) {
            addCriterion("P_CAPTAIN <>", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainGreaterThan(String value) {
            addCriterion("P_CAPTAIN >", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainGreaterThanOrEqualTo(String value) {
            addCriterion("P_CAPTAIN >=", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainLessThan(String value) {
            addCriterion("P_CAPTAIN <", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainLessThanOrEqualTo(String value) {
            addCriterion("P_CAPTAIN <=", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainLike(String value) {
            addCriterion("P_CAPTAIN like", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainNotLike(String value) {
            addCriterion("P_CAPTAIN not like", value, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainIn(List<String> values) {
            addCriterion("P_CAPTAIN in", values, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainNotIn(List<String> values) {
            addCriterion("P_CAPTAIN not in", values, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainBetween(String value1, String value2) {
            addCriterion("P_CAPTAIN between", value1, value2, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andPCaptainNotBetween(String value1, String value2) {
            addCriterion("P_CAPTAIN not between", value1, value2, "pCaptain");
            return (Criteria) this;
        }

        public Criteria andFNameIsNull() {
            addCriterion("F_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFNameIsNotNull() {
            addCriterion("F_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFNameEqualTo(String value) {
            addCriterion("F_NAME =", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotEqualTo(String value) {
            addCriterion("F_NAME <>", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThan(String value) {
            addCriterion("F_NAME >", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThanOrEqualTo(String value) {
            addCriterion("F_NAME >=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThan(String value) {
            addCriterion("F_NAME <", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThanOrEqualTo(String value) {
            addCriterion("F_NAME <=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLike(String value) {
            addCriterion("F_NAME like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotLike(String value) {
            addCriterion("F_NAME not like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameIn(List<String> values) {
            addCriterion("F_NAME in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotIn(List<String> values) {
            addCriterion("F_NAME not in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameBetween(String value1, String value2) {
            addCriterion("F_NAME between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotBetween(String value1, String value2) {
            addCriterion("F_NAME not between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFCaptainIsNull() {
            addCriterion("F_CAPTAIN is null");
            return (Criteria) this;
        }

        public Criteria andFCaptainIsNotNull() {
            addCriterion("F_CAPTAIN is not null");
            return (Criteria) this;
        }

        public Criteria andFCaptainEqualTo(String value) {
            addCriterion("F_CAPTAIN =", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainNotEqualTo(String value) {
            addCriterion("F_CAPTAIN <>", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainGreaterThan(String value) {
            addCriterion("F_CAPTAIN >", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainGreaterThanOrEqualTo(String value) {
            addCriterion("F_CAPTAIN >=", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainLessThan(String value) {
            addCriterion("F_CAPTAIN <", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainLessThanOrEqualTo(String value) {
            addCriterion("F_CAPTAIN <=", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainLike(String value) {
            addCriterion("F_CAPTAIN like", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainNotLike(String value) {
            addCriterion("F_CAPTAIN not like", value, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainIn(List<String> values) {
            addCriterion("F_CAPTAIN in", values, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainNotIn(List<String> values) {
            addCriterion("F_CAPTAIN not in", values, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainBetween(String value1, String value2) {
            addCriterion("F_CAPTAIN between", value1, value2, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFCaptainNotBetween(String value1, String value2) {
            addCriterion("F_CAPTAIN not between", value1, value2, "fCaptain");
            return (Criteria) this;
        }

        public Criteria andFPhoneIsNull() {
            addCriterion("F_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andFPhoneIsNotNull() {
            addCriterion("F_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andFPhoneEqualTo(String value) {
            addCriterion("F_PHONE =", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneNotEqualTo(String value) {
            addCriterion("F_PHONE <>", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneGreaterThan(String value) {
            addCriterion("F_PHONE >", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("F_PHONE >=", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneLessThan(String value) {
            addCriterion("F_PHONE <", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneLessThanOrEqualTo(String value) {
            addCriterion("F_PHONE <=", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneLike(String value) {
            addCriterion("F_PHONE like", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneNotLike(String value) {
            addCriterion("F_PHONE not like", value, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneIn(List<String> values) {
            addCriterion("F_PHONE in", values, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneNotIn(List<String> values) {
            addCriterion("F_PHONE not in", values, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneBetween(String value1, String value2) {
            addCriterion("F_PHONE between", value1, value2, "fPhone");
            return (Criteria) this;
        }

        public Criteria andFPhoneNotBetween(String value1, String value2) {
            addCriterion("F_PHONE not between", value1, value2, "fPhone");
            return (Criteria) this;
        }

        public Criteria andSNameIsNull() {
            addCriterion("S_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("S_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("S_NAME =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("S_NAME <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("S_NAME >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("S_NAME >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("S_NAME <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("S_NAME <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("S_NAME like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("S_NAME not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("S_NAME in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("S_NAME not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("S_NAME between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("S_NAME not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSCaptainIsNull() {
            addCriterion("S_CAPTAIN is null");
            return (Criteria) this;
        }

        public Criteria andSCaptainIsNotNull() {
            addCriterion("S_CAPTAIN is not null");
            return (Criteria) this;
        }

        public Criteria andSCaptainEqualTo(String value) {
            addCriterion("S_CAPTAIN =", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainNotEqualTo(String value) {
            addCriterion("S_CAPTAIN <>", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainGreaterThan(String value) {
            addCriterion("S_CAPTAIN >", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainGreaterThanOrEqualTo(String value) {
            addCriterion("S_CAPTAIN >=", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainLessThan(String value) {
            addCriterion("S_CAPTAIN <", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainLessThanOrEqualTo(String value) {
            addCriterion("S_CAPTAIN <=", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainLike(String value) {
            addCriterion("S_CAPTAIN like", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainNotLike(String value) {
            addCriterion("S_CAPTAIN not like", value, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainIn(List<String> values) {
            addCriterion("S_CAPTAIN in", values, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainNotIn(List<String> values) {
            addCriterion("S_CAPTAIN not in", values, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainBetween(String value1, String value2) {
            addCriterion("S_CAPTAIN between", value1, value2, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSCaptainNotBetween(String value1, String value2) {
            addCriterion("S_CAPTAIN not between", value1, value2, "sCaptain");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNull() {
            addCriterion("S_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNotNull() {
            addCriterion("S_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andSPhoneEqualTo(String value) {
            addCriterion("S_PHONE =", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotEqualTo(String value) {
            addCriterion("S_PHONE <>", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThan(String value) {
            addCriterion("S_PHONE >", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("S_PHONE >=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThan(String value) {
            addCriterion("S_PHONE <", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThanOrEqualTo(String value) {
            addCriterion("S_PHONE <=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLike(String value) {
            addCriterion("S_PHONE like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotLike(String value) {
            addCriterion("S_PHONE not like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneIn(List<String> values) {
            addCriterion("S_PHONE in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotIn(List<String> values) {
            addCriterion("S_PHONE not in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneBetween(String value1, String value2) {
            addCriterion("S_PHONE between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotBetween(String value1, String value2) {
            addCriterion("S_PHONE not between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andPRemarkIsNull() {
            addCriterion("P_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andPRemarkIsNotNull() {
            addCriterion("P_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andPRemarkEqualTo(String value) {
            addCriterion("P_REMARK =", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotEqualTo(String value) {
            addCriterion("P_REMARK <>", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkGreaterThan(String value) {
            addCriterion("P_REMARK >", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("P_REMARK >=", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLessThan(String value) {
            addCriterion("P_REMARK <", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLessThanOrEqualTo(String value) {
            addCriterion("P_REMARK <=", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkLike(String value) {
            addCriterion("P_REMARK like", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotLike(String value) {
            addCriterion("P_REMARK not like", value, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkIn(List<String> values) {
            addCriterion("P_REMARK in", values, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotIn(List<String> values) {
            addCriterion("P_REMARK not in", values, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkBetween(String value1, String value2) {
            addCriterion("P_REMARK between", value1, value2, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPRemarkNotBetween(String value1, String value2) {
            addCriterion("P_REMARK not between", value1, value2, "pRemark");
            return (Criteria) this;
        }

        public Criteria andPStateIsNull() {
            addCriterion("P_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPStateIsNotNull() {
            addCriterion("P_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPStateEqualTo(BigDecimal value) {
            addCriterion("P_STATE =", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateNotEqualTo(BigDecimal value) {
            addCriterion("P_STATE <>", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateGreaterThan(BigDecimal value) {
            addCriterion("P_STATE >", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_STATE >=", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateLessThan(BigDecimal value) {
            addCriterion("P_STATE <", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_STATE <=", value, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateIn(List<BigDecimal> values) {
            addCriterion("P_STATE in", values, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateNotIn(List<BigDecimal> values) {
            addCriterion("P_STATE not in", values, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_STATE between", value1, value2, "pState");
            return (Criteria) this;
        }

        public Criteria andPStateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_STATE not between", value1, value2, "pState");
            return (Criteria) this;
        }

        public Criteria andPProgressIsNull() {
            addCriterion("P_PROGRESS is null");
            return (Criteria) this;
        }

        public Criteria andPProgressIsNotNull() {
            addCriterion("P_PROGRESS is not null");
            return (Criteria) this;
        }

        public Criteria andPProgressEqualTo(String value) {
            addCriterion("P_PROGRESS =", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressNotEqualTo(String value) {
            addCriterion("P_PROGRESS <>", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressGreaterThan(String value) {
            addCriterion("P_PROGRESS >", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressGreaterThanOrEqualTo(String value) {
            addCriterion("P_PROGRESS >=", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressLessThan(String value) {
            addCriterion("P_PROGRESS <", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressLessThanOrEqualTo(String value) {
            addCriterion("P_PROGRESS <=", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressLike(String value) {
            addCriterion("P_PROGRESS like", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressNotLike(String value) {
            addCriterion("P_PROGRESS not like", value, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressIn(List<String> values) {
            addCriterion("P_PROGRESS in", values, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressNotIn(List<String> values) {
            addCriterion("P_PROGRESS not in", values, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressBetween(String value1, String value2) {
            addCriterion("P_PROGRESS between", value1, value2, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPProgressNotBetween(String value1, String value2) {
            addCriterion("P_PROGRESS not between", value1, value2, "pProgress");
            return (Criteria) this;
        }

        public Criteria andPTimeIsNull() {
            addCriterion("P_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPTimeIsNotNull() {
            addCriterion("P_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPTimeEqualTo(Date value) {
            addCriterion("P_TIME =", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeNotEqualTo(Date value) {
            addCriterion("P_TIME <>", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeGreaterThan(Date value) {
            addCriterion("P_TIME >", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("P_TIME >=", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeLessThan(Date value) {
            addCriterion("P_TIME <", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeLessThanOrEqualTo(Date value) {
            addCriterion("P_TIME <=", value, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeIn(List<Date> values) {
            addCriterion("P_TIME in", values, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeNotIn(List<Date> values) {
            addCriterion("P_TIME not in", values, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeBetween(Date value1, Date value2) {
            addCriterion("P_TIME between", value1, value2, "pTime");
            return (Criteria) this;
        }

        public Criteria andPTimeNotBetween(Date value1, Date value2) {
            addCriterion("P_TIME not between", value1, value2, "pTime");
            return (Criteria) this;
        }

        public Criteria andPCCaptainIsNull() {
            addCriterion("P_C_CAPTAIN is null");
            return (Criteria) this;
        }

        public Criteria andPCCaptainIsNotNull() {
            addCriterion("P_C_CAPTAIN is not null");
            return (Criteria) this;
        }

        public Criteria andPCCaptainEqualTo(String value) {
            addCriterion("P_C_CAPTAIN =", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainNotEqualTo(String value) {
            addCriterion("P_C_CAPTAIN <>", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainGreaterThan(String value) {
            addCriterion("P_C_CAPTAIN >", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainGreaterThanOrEqualTo(String value) {
            addCriterion("P_C_CAPTAIN >=", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainLessThan(String value) {
            addCriterion("P_C_CAPTAIN <", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainLessThanOrEqualTo(String value) {
            addCriterion("P_C_CAPTAIN <=", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainLike(String value) {
            addCriterion("P_C_CAPTAIN like", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainNotLike(String value) {
            addCriterion("P_C_CAPTAIN not like", value, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainIn(List<String> values) {
            addCriterion("P_C_CAPTAIN in", values, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainNotIn(List<String> values) {
            addCriterion("P_C_CAPTAIN not in", values, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainBetween(String value1, String value2) {
            addCriterion("P_C_CAPTAIN between", value1, value2, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPCCaptainNotBetween(String value1, String value2) {
            addCriterion("P_C_CAPTAIN not between", value1, value2, "pCCaptain");
            return (Criteria) this;
        }

        public Criteria andPScheduleIsNull() {
            addCriterion("P_SCHEDULE is null");
            return (Criteria) this;
        }

        public Criteria andPScheduleIsNotNull() {
            addCriterion("P_SCHEDULE is not null");
            return (Criteria) this;
        }

        public Criteria andPScheduleEqualTo(String value) {
            addCriterion("P_SCHEDULE =", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotEqualTo(String value) {
            addCriterion("P_SCHEDULE <>", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleGreaterThan(String value) {
            addCriterion("P_SCHEDULE >", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleGreaterThanOrEqualTo(String value) {
            addCriterion("P_SCHEDULE >=", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLessThan(String value) {
            addCriterion("P_SCHEDULE <", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLessThanOrEqualTo(String value) {
            addCriterion("P_SCHEDULE <=", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLike(String value) {
            addCriterion("P_SCHEDULE like", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotLike(String value) {
            addCriterion("P_SCHEDULE not like", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleIn(List<String> values) {
            addCriterion("P_SCHEDULE in", values, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotIn(List<String> values) {
            addCriterion("P_SCHEDULE not in", values, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleBetween(String value1, String value2) {
            addCriterion("P_SCHEDULE between", value1, value2, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotBetween(String value1, String value2) {
            addCriterion("P_SCHEDULE not between", value1, value2, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPFTypeIsNull() {
            addCriterion("P_F_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPFTypeIsNotNull() {
            addCriterion("P_F_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPFTypeEqualTo(BigDecimal value) {
            addCriterion("P_F_TYPE =", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeNotEqualTo(BigDecimal value) {
            addCriterion("P_F_TYPE <>", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeGreaterThan(BigDecimal value) {
            addCriterion("P_F_TYPE >", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_F_TYPE >=", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeLessThan(BigDecimal value) {
            addCriterion("P_F_TYPE <", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_F_TYPE <=", value, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeIn(List<BigDecimal> values) {
            addCriterion("P_F_TYPE in", values, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeNotIn(List<BigDecimal> values) {
            addCriterion("P_F_TYPE not in", values, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_F_TYPE between", value1, value2, "pFType");
            return (Criteria) this;
        }

        public Criteria andPFTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_F_TYPE not between", value1, value2, "pFType");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(BigDecimal value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(BigDecimal value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(BigDecimal value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(BigDecimal value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<BigDecimal> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<BigDecimal> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andPSourceIsNull() {
            addCriterion("P_SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andPSourceIsNotNull() {
            addCriterion("P_SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andPSourceEqualTo(String value) {
            addCriterion("P_SOURCE =", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotEqualTo(String value) {
            addCriterion("P_SOURCE <>", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceGreaterThan(String value) {
            addCriterion("P_SOURCE >", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceGreaterThanOrEqualTo(String value) {
            addCriterion("P_SOURCE >=", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLessThan(String value) {
            addCriterion("P_SOURCE <", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLessThanOrEqualTo(String value) {
            addCriterion("P_SOURCE <=", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceLike(String value) {
            addCriterion("P_SOURCE like", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotLike(String value) {
            addCriterion("P_SOURCE not like", value, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceIn(List<String> values) {
            addCriterion("P_SOURCE in", values, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotIn(List<String> values) {
            addCriterion("P_SOURCE not in", values, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceBetween(String value1, String value2) {
            addCriterion("P_SOURCE between", value1, value2, "pSource");
            return (Criteria) this;
        }

        public Criteria andPSourceNotBetween(String value1, String value2) {
            addCriterion("P_SOURCE not between", value1, value2, "pSource");
            return (Criteria) this;
        }

        public Criteria andPlanIsIsNull() {
            addCriterion("PLAN_IS is null");
            return (Criteria) this;
        }

        public Criteria andPlanIsIsNotNull() {
            addCriterion("PLAN_IS is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIsEqualTo(BigDecimal value) {
            addCriterion("PLAN_IS =", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsNotEqualTo(BigDecimal value) {
            addCriterion("PLAN_IS <>", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsGreaterThan(BigDecimal value) {
            addCriterion("PLAN_IS >", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAN_IS >=", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsLessThan(BigDecimal value) {
            addCriterion("PLAN_IS <", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAN_IS <=", value, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsIn(List<BigDecimal> values) {
            addCriterion("PLAN_IS in", values, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsNotIn(List<BigDecimal> values) {
            addCriterion("PLAN_IS not in", values, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAN_IS between", value1, value2, "planIs");
            return (Criteria) this;
        }

        public Criteria andPlanIsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAN_IS not between", value1, value2, "planIs");
            return (Criteria) this;
        }

        public Criteria andRIsIsNull() {
            addCriterion("R_IS is null");
            return (Criteria) this;
        }

        public Criteria andRIsIsNotNull() {
            addCriterion("R_IS is not null");
            return (Criteria) this;
        }

        public Criteria andRIsEqualTo(BigDecimal value) {
            addCriterion("R_IS =", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsNotEqualTo(BigDecimal value) {
            addCriterion("R_IS <>", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsGreaterThan(BigDecimal value) {
            addCriterion("R_IS >", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("R_IS >=", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsLessThan(BigDecimal value) {
            addCriterion("R_IS <", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("R_IS <=", value, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsIn(List<BigDecimal> values) {
            addCriterion("R_IS in", values, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsNotIn(List<BigDecimal> values) {
            addCriterion("R_IS not in", values, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("R_IS between", value1, value2, "rIs");
            return (Criteria) this;
        }

        public Criteria andRIsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("R_IS not between", value1, value2, "rIs");
            return (Criteria) this;
        }

        public Criteria andSIsIsNull() {
            addCriterion("S_IS is null");
            return (Criteria) this;
        }

        public Criteria andSIsIsNotNull() {
            addCriterion("S_IS is not null");
            return (Criteria) this;
        }

        public Criteria andSIsEqualTo(BigDecimal value) {
            addCriterion("S_IS =", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsNotEqualTo(BigDecimal value) {
            addCriterion("S_IS <>", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsGreaterThan(BigDecimal value) {
            addCriterion("S_IS >", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_IS >=", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsLessThan(BigDecimal value) {
            addCriterion("S_IS <", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_IS <=", value, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsIn(List<BigDecimal> values) {
            addCriterion("S_IS in", values, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsNotIn(List<BigDecimal> values) {
            addCriterion("S_IS not in", values, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_IS between", value1, value2, "sIs");
            return (Criteria) this;
        }

        public Criteria andSIsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_IS not between", value1, value2, "sIs");
            return (Criteria) this;
        }

        public Criteria andPStartTimeIsNull() {
            addCriterion("P_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPStartTimeIsNotNull() {
            addCriterion("P_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPStartTimeEqualTo(Date value) {
            addCriterion("P_START_TIME =", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeNotEqualTo(Date value) {
            addCriterion("P_START_TIME <>", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeGreaterThan(Date value) {
            addCriterion("P_START_TIME >", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("P_START_TIME >=", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeLessThan(Date value) {
            addCriterion("P_START_TIME <", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("P_START_TIME <=", value, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeIn(List<Date> values) {
            addCriterion("P_START_TIME in", values, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeNotIn(List<Date> values) {
            addCriterion("P_START_TIME not in", values, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeBetween(Date value1, Date value2) {
            addCriterion("P_START_TIME between", value1, value2, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("P_START_TIME not between", value1, value2, "pStartTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIsNull() {
            addCriterion("P_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIsNotNull() {
            addCriterion("P_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPEndTimeEqualTo(Date value) {
            addCriterion("P_END_TIME =", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotEqualTo(Date value) {
            addCriterion("P_END_TIME <>", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeGreaterThan(Date value) {
            addCriterion("P_END_TIME >", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("P_END_TIME >=", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeLessThan(Date value) {
            addCriterion("P_END_TIME <", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("P_END_TIME <=", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIn(List<Date> values) {
            addCriterion("P_END_TIME in", values, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotIn(List<Date> values) {
            addCriterion("P_END_TIME not in", values, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeBetween(Date value1, Date value2) {
            addCriterion("P_END_TIME between", value1, value2, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("P_END_TIME not between", value1, value2, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("R_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("R_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("R_NAME =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("R_NAME <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("R_NAME >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("R_NAME >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("R_NAME <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("R_NAME <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("R_NAME like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("R_NAME not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("R_NAME in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("R_NAME not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("R_NAME between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("R_NAME not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRCaptainIsNull() {
            addCriterion("R_CAPTAIN is null");
            return (Criteria) this;
        }

        public Criteria andRCaptainIsNotNull() {
            addCriterion("R_CAPTAIN is not null");
            return (Criteria) this;
        }

        public Criteria andRCaptainEqualTo(String value) {
            addCriterion("R_CAPTAIN =", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainNotEqualTo(String value) {
            addCriterion("R_CAPTAIN <>", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainGreaterThan(String value) {
            addCriterion("R_CAPTAIN >", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainGreaterThanOrEqualTo(String value) {
            addCriterion("R_CAPTAIN >=", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainLessThan(String value) {
            addCriterion("R_CAPTAIN <", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainLessThanOrEqualTo(String value) {
            addCriterion("R_CAPTAIN <=", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainLike(String value) {
            addCriterion("R_CAPTAIN like", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainNotLike(String value) {
            addCriterion("R_CAPTAIN not like", value, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainIn(List<String> values) {
            addCriterion("R_CAPTAIN in", values, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainNotIn(List<String> values) {
            addCriterion("R_CAPTAIN not in", values, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainBetween(String value1, String value2) {
            addCriterion("R_CAPTAIN between", value1, value2, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRCaptainNotBetween(String value1, String value2) {
            addCriterion("R_CAPTAIN not between", value1, value2, "rCaptain");
            return (Criteria) this;
        }

        public Criteria andRPhoneIsNull() {
            addCriterion("R_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andRPhoneIsNotNull() {
            addCriterion("R_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andRPhoneEqualTo(String value) {
            addCriterion("R_PHONE =", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotEqualTo(String value) {
            addCriterion("R_PHONE <>", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneGreaterThan(String value) {
            addCriterion("R_PHONE >", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("R_PHONE >=", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLessThan(String value) {
            addCriterion("R_PHONE <", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLessThanOrEqualTo(String value) {
            addCriterion("R_PHONE <=", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLike(String value) {
            addCriterion("R_PHONE like", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotLike(String value) {
            addCriterion("R_PHONE not like", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneIn(List<String> values) {
            addCriterion("R_PHONE in", values, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotIn(List<String> values) {
            addCriterion("R_PHONE not in", values, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneBetween(String value1, String value2) {
            addCriterion("R_PHONE between", value1, value2, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotBetween(String value1, String value2) {
            addCriterion("R_PHONE not between", value1, value2, "rPhone");
            return (Criteria) this;
        }

        public Criteria andFIsIsNull() {
            addCriterion("F_IS is null");
            return (Criteria) this;
        }

        public Criteria andFIsIsNotNull() {
            addCriterion("F_IS is not null");
            return (Criteria) this;
        }

        public Criteria andFIsEqualTo(BigDecimal value) {
            addCriterion("F_IS =", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsNotEqualTo(BigDecimal value) {
            addCriterion("F_IS <>", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsGreaterThan(BigDecimal value) {
            addCriterion("F_IS >", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_IS >=", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsLessThan(BigDecimal value) {
            addCriterion("F_IS <", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_IS <=", value, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsIn(List<BigDecimal> values) {
            addCriterion("F_IS in", values, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsNotIn(List<BigDecimal> values) {
            addCriterion("F_IS not in", values, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_IS between", value1, value2, "fIs");
            return (Criteria) this;
        }

        public Criteria andFIsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_IS not between", value1, value2, "fIs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROJECT
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 21 13:49:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROJECT
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}