package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class ProjectType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT_TYPE.ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT_TYPE.TYPE_NAME
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT_TYPE.P_T_STATE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    private BigDecimal pTState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT_TYPE.F_ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    private BigDecimal fId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT_TYPE.ID
     *
     * @return the value of TB_PROJECT_TYPE.ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT_TYPE.ID
     *
     * @param id the value for TB_PROJECT_TYPE.ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT_TYPE.TYPE_NAME
     *
     * @return the value of TB_PROJECT_TYPE.TYPE_NAME
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT_TYPE.TYPE_NAME
     *
     * @param typeName the value for TB_PROJECT_TYPE.TYPE_NAME
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT_TYPE.P_T_STATE
     *
     * @return the value of TB_PROJECT_TYPE.P_T_STATE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public BigDecimal getpTState() {
        return pTState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT_TYPE.P_T_STATE
     *
     * @param pTState the value for TB_PROJECT_TYPE.P_T_STATE
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public void setpTState(BigDecimal pTState) {
        this.pTState = pTState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT_TYPE.F_ID
     *
     * @return the value of TB_PROJECT_TYPE.F_ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public BigDecimal getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT_TYPE.F_ID
     *
     * @param fId the value for TB_PROJECT_TYPE.F_ID
     *
     * @mbg.generated Tue Dec 25 12:53:23 CST 2018
     */
    public void setfId(BigDecimal fId) {
        this.fId = fId;
    }
}