package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProjectFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.P_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.F_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private BigDecimal fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.FILE_NAME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.FILE_URL
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.FILE_TIME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private Date fileTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.U_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private BigDecimal uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_P_BASIC_FILE.F_STATE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    private BigDecimal fState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.ID
     *
     * @return the value of TB_P_BASIC_FILE.ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.ID
     *
     * @param id the value for TB_P_BASIC_FILE.ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.P_ID
     *
     * @return the value of TB_P_BASIC_FILE.P_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.P_ID
     *
     * @param pId the value for TB_P_BASIC_FILE.P_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.F_ID
     *
     * @return the value of TB_P_BASIC_FILE.F_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public BigDecimal getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.F_ID
     *
     * @param fId the value for TB_P_BASIC_FILE.F_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setfId(BigDecimal fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.FILE_NAME
     *
     * @return the value of TB_P_BASIC_FILE.FILE_NAME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.FILE_NAME
     *
     * @param fileName the value for TB_P_BASIC_FILE.FILE_NAME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.FILE_URL
     *
     * @return the value of TB_P_BASIC_FILE.FILE_URL
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.FILE_URL
     *
     * @param fileUrl the value for TB_P_BASIC_FILE.FILE_URL
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.FILE_TIME
     *
     * @return the value of TB_P_BASIC_FILE.FILE_TIME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public Date getFileTime() {
        return fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.FILE_TIME
     *
     * @param fileTime the value for TB_P_BASIC_FILE.FILE_TIME
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setFileTime(Date fileTime) {
        this.fileTime = fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.U_ID
     *
     * @return the value of TB_P_BASIC_FILE.U_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public BigDecimal getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.U_ID
     *
     * @param uId the value for TB_P_BASIC_FILE.U_ID
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setuId(BigDecimal uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_P_BASIC_FILE.F_STATE
     *
     * @return the value of TB_P_BASIC_FILE.F_STATE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public BigDecimal getfState() {
        return fState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_P_BASIC_FILE.F_STATE
     *
     * @param fState the value for TB_P_BASIC_FILE.F_STATE
     *
     * @mbg.generated Mon Jan 14 09:58:54 CST 2019
     */
    public void setfState(BigDecimal fState) {
        this.fState = fState;
    }

    @Override
    public String toString() {
        return "ProjectFile{" +
                "id=" + id +
                ", pId='" + pId + '\'' +
                ", fId=" + fId +
                ", fileName='" + fileName + '\'' +
                ", fileUrl='" + fileUrl + '\'' +
                ", fileTime=" + fileTime +
                ", uId=" + uId +
                ", fState=" + fState +
                '}';
    }
}