package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_NUMBER
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal pType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_ADDRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_SUMMARY
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pCaptain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.F_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.F_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String fCaptain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.F_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String fPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.S_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.S_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String sCaptain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.S_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_REMARK
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_STATE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal pState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_PROGRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pProgress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private Date pTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_C_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pCCaptain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_SCHEDULE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_F_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal pFType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.U_ID
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_SOURCE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String pSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.PLAN_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal planIs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.R_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal rIs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.S_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal sIs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_START_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private Date pStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.P_END_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private Date pEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.R_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.R_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String rCaptain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.R_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private String rPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROJECT.F_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    private BigDecimal fIs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_NUMBER
     *
     * @return the value of TB_PROJECT.P_NUMBER
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpNumber() {
        return pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_NUMBER
     *
     * @param pNumber the value for TB_PROJECT.P_NUMBER
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpNumber(String pNumber) {
        this.pNumber = pNumber == null ? null : pNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_NAME
     *
     * @return the value of TB_PROJECT.P_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_NAME
     *
     * @param pName the value for TB_PROJECT.P_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_TYPE
     *
     * @return the value of TB_PROJECT.P_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_TYPE
     *
     * @param pType the value for TB_PROJECT.P_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpType(BigDecimal pType) {
        this.pType = pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_ADDRESS
     *
     * @return the value of TB_PROJECT.P_ADDRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpAddress() {
        return pAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_ADDRESS
     *
     * @param pAddress the value for TB_PROJECT.P_ADDRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpAddress(String pAddress) {
        this.pAddress = pAddress == null ? null : pAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_SUMMARY
     *
     * @return the value of TB_PROJECT.P_SUMMARY
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpSummary() {
        return pSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_SUMMARY
     *
     * @param pSummary the value for TB_PROJECT.P_SUMMARY
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpSummary(String pSummary) {
        this.pSummary = pSummary == null ? null : pSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_CAPTAIN
     *
     * @return the value of TB_PROJECT.P_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpCaptain() {
        return pCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_CAPTAIN
     *
     * @param pCaptain the value for TB_PROJECT.P_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpCaptain(String pCaptain) {
        this.pCaptain = pCaptain == null ? null : pCaptain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.F_NAME
     *
     * @return the value of TB_PROJECT.F_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.F_NAME
     *
     * @param fName the value for TB_PROJECT.F_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.F_CAPTAIN
     *
     * @return the value of TB_PROJECT.F_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getfCaptain() {
        return fCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.F_CAPTAIN
     *
     * @param fCaptain the value for TB_PROJECT.F_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setfCaptain(String fCaptain) {
        this.fCaptain = fCaptain == null ? null : fCaptain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.F_PHONE
     *
     * @return the value of TB_PROJECT.F_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getfPhone() {
        return fPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.F_PHONE
     *
     * @param fPhone the value for TB_PROJECT.F_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setfPhone(String fPhone) {
        this.fPhone = fPhone == null ? null : fPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.S_NAME
     *
     * @return the value of TB_PROJECT.S_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.S_NAME
     *
     * @param sName the value for TB_PROJECT.S_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.S_CAPTAIN
     *
     * @return the value of TB_PROJECT.S_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getsCaptain() {
        return sCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.S_CAPTAIN
     *
     * @param sCaptain the value for TB_PROJECT.S_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setsCaptain(String sCaptain) {
        this.sCaptain = sCaptain == null ? null : sCaptain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.S_PHONE
     *
     * @return the value of TB_PROJECT.S_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.S_PHONE
     *
     * @param sPhone the value for TB_PROJECT.S_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_REMARK
     *
     * @return the value of TB_PROJECT.P_REMARK
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpRemark() {
        return pRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_REMARK
     *
     * @param pRemark the value for TB_PROJECT.P_REMARK
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpRemark(String pRemark) {
        this.pRemark = pRemark == null ? null : pRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_STATE
     *
     * @return the value of TB_PROJECT.P_STATE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getpState() {
        return pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_STATE
     *
     * @param pState the value for TB_PROJECT.P_STATE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpState(BigDecimal pState) {
        this.pState = pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_PROGRESS
     *
     * @return the value of TB_PROJECT.P_PROGRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpProgress() {
        return pProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_PROGRESS
     *
     * @param pProgress the value for TB_PROJECT.P_PROGRESS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpProgress(String pProgress) {
        this.pProgress = pProgress == null ? null : pProgress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_TIME
     *
     * @return the value of TB_PROJECT.P_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public Date getpTime() {
        return pTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_TIME
     *
     * @param pTime the value for TB_PROJECT.P_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpTime(Date pTime) {
        this.pTime = pTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_C_CAPTAIN
     *
     * @return the value of TB_PROJECT.P_C_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpCCaptain() {
        return pCCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_C_CAPTAIN
     *
     * @param pCCaptain the value for TB_PROJECT.P_C_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpCCaptain(String pCCaptain) {
        this.pCCaptain = pCCaptain == null ? null : pCCaptain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_SCHEDULE
     *
     * @return the value of TB_PROJECT.P_SCHEDULE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpSchedule() {
        return pSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_SCHEDULE
     *
     * @param pSchedule the value for TB_PROJECT.P_SCHEDULE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpSchedule(String pSchedule) {
        this.pSchedule = pSchedule == null ? null : pSchedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_F_TYPE
     *
     * @return the value of TB_PROJECT.P_F_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getpFType() {
        return pFType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_F_TYPE
     *
     * @param pFType the value for TB_PROJECT.P_F_TYPE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpFType(BigDecimal pFType) {
        this.pFType = pFType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.U_ID
     *
     * @return the value of TB_PROJECT.U_ID
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.U_ID
     *
     * @param uId the value for TB_PROJECT.U_ID
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setuId(BigDecimal uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_SOURCE
     *
     * @return the value of TB_PROJECT.P_SOURCE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getpSource() {
        return pSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_SOURCE
     *
     * @param pSource the value for TB_PROJECT.P_SOURCE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpSource(String pSource) {
        this.pSource = pSource == null ? null : pSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.PLAN_IS
     *
     * @return the value of TB_PROJECT.PLAN_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getPlanIs() {
        return planIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.PLAN_IS
     *
     * @param planIs the value for TB_PROJECT.PLAN_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setPlanIs(BigDecimal planIs) {
        this.planIs = planIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.R_IS
     *
     * @return the value of TB_PROJECT.R_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getrIs() {
        return rIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.R_IS
     *
     * @param rIs the value for TB_PROJECT.R_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setrIs(BigDecimal rIs) {
        this.rIs = rIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.S_IS
     *
     * @return the value of TB_PROJECT.S_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getsIs() {
        return sIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.S_IS
     *
     * @param sIs the value for TB_PROJECT.S_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setsIs(BigDecimal sIs) {
        this.sIs = sIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_START_TIME
     *
     * @return the value of TB_PROJECT.P_START_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public Date getpStartTime() {
        return pStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_START_TIME
     *
     * @param pStartTime the value for TB_PROJECT.P_START_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpStartTime(Date pStartTime) {
        this.pStartTime = pStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.P_END_TIME
     *
     * @return the value of TB_PROJECT.P_END_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public Date getpEndTime() {
        return pEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.P_END_TIME
     *
     * @param pEndTime the value for TB_PROJECT.P_END_TIME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setpEndTime(Date pEndTime) {
        this.pEndTime = pEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.R_NAME
     *
     * @return the value of TB_PROJECT.R_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.R_NAME
     *
     * @param rName the value for TB_PROJECT.R_NAME
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.R_CAPTAIN
     *
     * @return the value of TB_PROJECT.R_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getrCaptain() {
        return rCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.R_CAPTAIN
     *
     * @param rCaptain the value for TB_PROJECT.R_CAPTAIN
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setrCaptain(String rCaptain) {
        this.rCaptain = rCaptain == null ? null : rCaptain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.R_PHONE
     *
     * @return the value of TB_PROJECT.R_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.R_PHONE
     *
     * @param rPhone the value for TB_PROJECT.R_PHONE
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone == null ? null : rPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROJECT.F_IS
     *
     * @return the value of TB_PROJECT.F_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public BigDecimal getfIs() {
        return fIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROJECT.F_IS
     *
     * @param fIs the value for TB_PROJECT.F_IS
     *
     * @mbg.generated Fri Dec 21 13:49:12 CST 2018
     */
    public void setfIs(BigDecimal fIs) {
        this.fIs = fIs;
    }

    @Override
    public String toString() {
        return "Project{" +
                "pNumber='" + pNumber + '\'' +
                ", pName='" + pName + '\'' +
                ", pType=" + pType +
                ", pAddress='" + pAddress + '\'' +
                ", pSummary='" + pSummary + '\'' +
                ", pCaptain='" + pCaptain + '\'' +
                ", fName='" + fName + '\'' +
                ", fCaptain='" + fCaptain + '\'' +
                ", fPhone='" + fPhone + '\'' +
                ", sName='" + sName + '\'' +
                ", sCaptain='" + sCaptain + '\'' +
                ", sPhone='" + sPhone + '\'' +
                ", pRemark='" + pRemark + '\'' +
                ", pState=" + pState +
                ", pProgress='" + pProgress + '\'' +
                ", pTime=" + pTime +
                ", pCCaptain='" + pCCaptain + '\'' +
                ", pSchedule='" + pSchedule + '\'' +
                ", pFType=" + pFType +
                ", uId=" + uId +
                ", pSource='" + pSource + '\'' +
                ", planIs=" + planIs +
                ", rIs=" + rIs +
                ", sIs=" + sIs +
                ", pStartTime=" + pStartTime +
                ", pEndTime=" + pEndTime +
                ", rName='" + rName + '\'' +
                ", rCaptain='" + rCaptain + '\'' +
                ", rPhone='" + rPhone + '\'' +
                ", fIs=" + fIs +
                '}';
    }
}