package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Record implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.P_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.U_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private BigDecimal uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.T_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private BigDecimal tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.PR_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private Date prTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.P_SCHEDULE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private String pSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.PS_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private BigDecimal psId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.CREAT_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PROCESS_RECORD.PR_STATE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    private BigDecimal prState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.ID
     *
     * @return the value of TB_PROCESS_RECORD.ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.ID
     *
     * @param id the value for TB_PROCESS_RECORD.ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.P_ID
     *
     * @return the value of TB_PROCESS_RECORD.P_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.P_ID
     *
     * @param pId the value for TB_PROCESS_RECORD.P_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.U_ID
     *
     * @return the value of TB_PROCESS_RECORD.U_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public BigDecimal getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.U_ID
     *
     * @param uId the value for TB_PROCESS_RECORD.U_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setuId(BigDecimal uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.T_ID
     *
     * @return the value of TB_PROCESS_RECORD.T_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public BigDecimal gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.T_ID
     *
     * @param tId the value for TB_PROCESS_RECORD.T_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void settId(BigDecimal tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.PR_TIME
     *
     * @return the value of TB_PROCESS_RECORD.PR_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public Date getPrTime() {
        return prTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.PR_TIME
     *
     * @param prTime the value for TB_PROCESS_RECORD.PR_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setPrTime(Date prTime) {
        this.prTime = prTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.P_SCHEDULE
     *
     * @return the value of TB_PROCESS_RECORD.P_SCHEDULE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public String getpSchedule() {
        return pSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.P_SCHEDULE
     *
     * @param pSchedule the value for TB_PROCESS_RECORD.P_SCHEDULE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setpSchedule(String pSchedule) {
        this.pSchedule = pSchedule == null ? null : pSchedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.PS_ID
     *
     * @return the value of TB_PROCESS_RECORD.PS_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public BigDecimal getPsId() {
        return psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.PS_ID
     *
     * @param psId the value for TB_PROCESS_RECORD.PS_ID
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setPsId(BigDecimal psId) {
        this.psId = psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.CREAT_TIME
     *
     * @return the value of TB_PROCESS_RECORD.CREAT_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.CREAT_TIME
     *
     * @param creatTime the value for TB_PROCESS_RECORD.CREAT_TIME
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PROCESS_RECORD.PR_STATE
     *
     * @return the value of TB_PROCESS_RECORD.PR_STATE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public BigDecimal getPrState() {
        return prState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PROCESS_RECORD.PR_STATE
     *
     * @param prState the value for TB_PROCESS_RECORD.PR_STATE
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setPrState(BigDecimal prState) {
        this.prState = prState;
    }

    @Override
    public String toString() {
        return "Record{" +
                "id=" + id +
                ", pId='" + pId + '\'' +
                ", uId=" + uId +
                ", tId=" + tId +
                ", prTime=" + prTime +
                ", pSchedule='" + pSchedule + '\'' +
                ", psId=" + psId +
                ", creatTime=" + creatTime +
                ", prState=" + prState +
                '}';
    }
}