package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordExample implements Serializable {
    protected int stratRow;
    protected int endRow;

    public int getStratRow() {
        return stratRow;
    }

    public void setStratRow(int stratRow) {
        this.stratRow = stratRow;
    }

    public int getEndRow() {
        return endRow;
    }

    public void setEndRow(int endRow) {
        this.endRow = endRow;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPIdIsNull() {
            addCriterion("P_ID is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("P_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(String value) {
            addCriterion("P_ID =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(String value) {
            addCriterion("P_ID <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(String value) {
            addCriterion("P_ID >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(String value) {
            addCriterion("P_ID >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(String value) {
            addCriterion("P_ID <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(String value) {
            addCriterion("P_ID <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLike(String value) {
            addCriterion("P_ID like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotLike(String value) {
            addCriterion("P_ID not like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<String> values) {
            addCriterion("P_ID in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<String> values) {
            addCriterion("P_ID not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(String value1, String value2) {
            addCriterion("P_ID between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(String value1, String value2) {
            addCriterion("P_ID not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(BigDecimal value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(BigDecimal value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(BigDecimal value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(BigDecimal value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<BigDecimal> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<BigDecimal> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andTIdIsNull() {
            addCriterion("T_ID is null");
            return (Criteria) this;
        }

        public Criteria andTIdIsNotNull() {
            addCriterion("T_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTIdEqualTo(BigDecimal value) {
            addCriterion("T_ID =", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotEqualTo(BigDecimal value) {
            addCriterion("T_ID <>", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdGreaterThan(BigDecimal value) {
            addCriterion("T_ID >", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("T_ID >=", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdLessThan(BigDecimal value) {
            addCriterion("T_ID <", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("T_ID <=", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdIn(List<BigDecimal> values) {
            addCriterion("T_ID in", values, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotIn(List<BigDecimal> values) {
            addCriterion("T_ID not in", values, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("T_ID between", value1, value2, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("T_ID not between", value1, value2, "tId");
            return (Criteria) this;
        }

        public Criteria andPrTimeIsNull() {
            addCriterion("PR_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPrTimeIsNotNull() {
            addCriterion("PR_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPrTimeEqualTo(Date value) {
            addCriterion("PR_TIME =", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeNotEqualTo(Date value) {
            addCriterion("PR_TIME <>", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeGreaterThan(Date value) {
            addCriterion("PR_TIME >", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PR_TIME >=", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeLessThan(Date value) {
            addCriterion("PR_TIME <", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeLessThanOrEqualTo(Date value) {
            addCriterion("PR_TIME <=", value, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeIn(List<Date> values) {
            addCriterion("PR_TIME in", values, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeNotIn(List<Date> values) {
            addCriterion("PR_TIME not in", values, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeBetween(Date value1, Date value2) {
            addCriterion("PR_TIME between", value1, value2, "prTime");
            return (Criteria) this;
        }

        public Criteria andPrTimeNotBetween(Date value1, Date value2) {
            addCriterion("PR_TIME not between", value1, value2, "prTime");
            return (Criteria) this;
        }

        public Criteria andPScheduleIsNull() {
            addCriterion("P_SCHEDULE is null");
            return (Criteria) this;
        }

        public Criteria andPScheduleIsNotNull() {
            addCriterion("P_SCHEDULE is not null");
            return (Criteria) this;
        }

        public Criteria andPScheduleEqualTo(String value) {
            addCriterion("P_SCHEDULE =", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotEqualTo(String value) {
            addCriterion("P_SCHEDULE <>", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleGreaterThan(String value) {
            addCriterion("P_SCHEDULE >", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleGreaterThanOrEqualTo(String value) {
            addCriterion("P_SCHEDULE >=", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLessThan(String value) {
            addCriterion("P_SCHEDULE <", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLessThanOrEqualTo(String value) {
            addCriterion("P_SCHEDULE <=", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleLike(String value) {
            addCriterion("P_SCHEDULE like", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotLike(String value) {
            addCriterion("P_SCHEDULE not like", value, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleIn(List<String> values) {
            addCriterion("P_SCHEDULE in", values, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotIn(List<String> values) {
            addCriterion("P_SCHEDULE not in", values, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleBetween(String value1, String value2) {
            addCriterion("P_SCHEDULE between", value1, value2, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPScheduleNotBetween(String value1, String value2) {
            addCriterion("P_SCHEDULE not between", value1, value2, "pSchedule");
            return (Criteria) this;
        }

        public Criteria andPsIdIsNull() {
            addCriterion("PS_ID is null");
            return (Criteria) this;
        }

        public Criteria andPsIdIsNotNull() {
            addCriterion("PS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPsIdEqualTo(BigDecimal value) {
            addCriterion("PS_ID =", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotEqualTo(BigDecimal value) {
            addCriterion("PS_ID <>", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdGreaterThan(BigDecimal value) {
            addCriterion("PS_ID >", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PS_ID >=", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdLessThan(BigDecimal value) {
            addCriterion("PS_ID <", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PS_ID <=", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdIn(List<BigDecimal> values) {
            addCriterion("PS_ID in", values, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotIn(List<BigDecimal> values) {
            addCriterion("PS_ID not in", values, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PS_ID between", value1, value2, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PS_ID not between", value1, value2, "psId");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("CREAT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("CREAT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("CREAT_TIME =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("CREAT_TIME <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("CREAT_TIME >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("CREAT_TIME <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("CREAT_TIME in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("CREAT_TIME not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andPrStateIsNull() {
            addCriterion("PR_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPrStateIsNotNull() {
            addCriterion("PR_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPrStateEqualTo(BigDecimal value) {
            addCriterion("PR_STATE =", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateNotEqualTo(BigDecimal value) {
            addCriterion("PR_STATE <>", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateGreaterThan(BigDecimal value) {
            addCriterion("PR_STATE >", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PR_STATE >=", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateLessThan(BigDecimal value) {
            addCriterion("PR_STATE <", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PR_STATE <=", value, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateIn(List<BigDecimal> values) {
            addCriterion("PR_STATE in", values, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateNotIn(List<BigDecimal> values) {
            addCriterion("PR_STATE not in", values, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PR_STATE between", value1, value2, "prState");
            return (Criteria) this;
        }

        public Criteria andPrStateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PR_STATE not between", value1, value2, "prState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 10:39:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PROCESS_RECORD
     *
     * @mbg.generated Wed Dec 26 10:39:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}