package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SkedExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public SkedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSYearIsNull() {
            addCriterion("S_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andSYearIsNotNull() {
            addCriterion("S_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andSYearEqualTo(BigDecimal value) {
            addCriterion("S_YEAR =", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearNotEqualTo(BigDecimal value) {
            addCriterion("S_YEAR <>", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearGreaterThan(BigDecimal value) {
            addCriterion("S_YEAR >", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_YEAR >=", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearLessThan(BigDecimal value) {
            addCriterion("S_YEAR <", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_YEAR <=", value, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearIn(List<BigDecimal> values) {
            addCriterion("S_YEAR in", values, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearNotIn(List<BigDecimal> values) {
            addCriterion("S_YEAR not in", values, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_YEAR between", value1, value2, "sYear");
            return (Criteria) this;
        }

        public Criteria andSYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_YEAR not between", value1, value2, "sYear");
            return (Criteria) this;
        }

        public Criteria andSMonthIsNull() {
            addCriterion("S_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andSMonthIsNotNull() {
            addCriterion("S_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andSMonthEqualTo(BigDecimal value) {
            addCriterion("S_MONTH =", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthNotEqualTo(BigDecimal value) {
            addCriterion("S_MONTH <>", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthGreaterThan(BigDecimal value) {
            addCriterion("S_MONTH >", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_MONTH >=", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthLessThan(BigDecimal value) {
            addCriterion("S_MONTH <", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_MONTH <=", value, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthIn(List<BigDecimal> values) {
            addCriterion("S_MONTH in", values, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthNotIn(List<BigDecimal> values) {
            addCriterion("S_MONTH not in", values, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_MONTH between", value1, value2, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSMonthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_MONTH not between", value1, value2, "sMonth");
            return (Criteria) this;
        }

        public Criteria andSDayIsNull() {
            addCriterion("S_DAY is null");
            return (Criteria) this;
        }

        public Criteria andSDayIsNotNull() {
            addCriterion("S_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andSDayEqualTo(BigDecimal value) {
            addCriterion("S_DAY =", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayNotEqualTo(BigDecimal value) {
            addCriterion("S_DAY <>", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayGreaterThan(BigDecimal value) {
            addCriterion("S_DAY >", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_DAY >=", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayLessThan(BigDecimal value) {
            addCriterion("S_DAY <", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_DAY <=", value, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayIn(List<BigDecimal> values) {
            addCriterion("S_DAY in", values, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayNotIn(List<BigDecimal> values) {
            addCriterion("S_DAY not in", values, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_DAY between", value1, value2, "sDay");
            return (Criteria) this;
        }

        public Criteria andSDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_DAY not between", value1, value2, "sDay");
            return (Criteria) this;
        }

        public Criteria andPIdIsNull() {
            addCriterion("P_ID is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("P_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(String value) {
            addCriterion("P_ID =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(String value) {
            addCriterion("P_ID <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(String value) {
            addCriterion("P_ID >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(String value) {
            addCriterion("P_ID >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(String value) {
            addCriterion("P_ID <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(String value) {
            addCriterion("P_ID <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLike(String value) {
            addCriterion("P_ID like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotLike(String value) {
            addCriterion("P_ID not like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<String> values) {
            addCriterion("P_ID in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<String> values) {
            addCriterion("P_ID not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(String value1, String value2) {
            addCriterion("P_ID between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(String value1, String value2) {
            addCriterion("P_ID not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPsIdIsNull() {
            addCriterion("PS_ID is null");
            return (Criteria) this;
        }

        public Criteria andPsIdIsNotNull() {
            addCriterion("PS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPsIdEqualTo(BigDecimal value) {
            addCriterion("PS_ID =", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotEqualTo(BigDecimal value) {
            addCriterion("PS_ID <>", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdGreaterThan(BigDecimal value) {
            addCriterion("PS_ID >", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PS_ID >=", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdLessThan(BigDecimal value) {
            addCriterion("PS_ID <", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PS_ID <=", value, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdIn(List<BigDecimal> values) {
            addCriterion("PS_ID in", values, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotIn(List<BigDecimal> values) {
            addCriterion("PS_ID not in", values, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PS_ID between", value1, value2, "psId");
            return (Criteria) this;
        }

        public Criteria andPsIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PS_ID not between", value1, value2, "psId");
            return (Criteria) this;
        }

        public Criteria andSStateIsNull() {
            addCriterion("S_STATE is null");
            return (Criteria) this;
        }

        public Criteria andSStateIsNotNull() {
            addCriterion("S_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andSStateEqualTo(BigDecimal value) {
            addCriterion("S_STATE =", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotEqualTo(BigDecimal value) {
            addCriterion("S_STATE <>", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateGreaterThan(BigDecimal value) {
            addCriterion("S_STATE >", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_STATE >=", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateLessThan(BigDecimal value) {
            addCriterion("S_STATE <", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_STATE <=", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateIn(List<BigDecimal> values) {
            addCriterion("S_STATE in", values, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotIn(List<BigDecimal> values) {
            addCriterion("S_STATE not in", values, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_STATE between", value1, value2, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_STATE not between", value1, value2, "sState");
            return (Criteria) this;
        }

        public Criteria andPsNameIsNull() {
            addCriterion("PS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPsNameIsNotNull() {
            addCriterion("PS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPsNameEqualTo(String value) {
            addCriterion("PS_NAME =", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameNotEqualTo(String value) {
            addCriterion("PS_NAME <>", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameGreaterThan(String value) {
            addCriterion("PS_NAME >", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameGreaterThanOrEqualTo(String value) {
            addCriterion("PS_NAME >=", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameLessThan(String value) {
            addCriterion("PS_NAME <", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameLessThanOrEqualTo(String value) {
            addCriterion("PS_NAME <=", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameLike(String value) {
            addCriterion("PS_NAME like", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameNotLike(String value) {
            addCriterion("PS_NAME not like", value, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameIn(List<String> values) {
            addCriterion("PS_NAME in", values, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameNotIn(List<String> values) {
            addCriterion("PS_NAME not in", values, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameBetween(String value1, String value2) {
            addCriterion("PS_NAME between", value1, value2, "psName");
            return (Criteria) this;
        }

        public Criteria andPsNameNotBetween(String value1, String value2) {
            addCriterion("PS_NAME not between", value1, value2, "psName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SKED
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 22 16:40:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SKED
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}