package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Sked implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.S_YEAR
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal sYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.S_MONTH
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal sMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.S_DAY
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal sDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.P_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.PS_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal psId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.S_STATE
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private BigDecimal sState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SKED.PS_NAME
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    private String psName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.ID
     *
     * @return the value of TB_SKED.ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.ID
     *
     * @param id the value for TB_SKED.ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.S_YEAR
     *
     * @return the value of TB_SKED.S_YEAR
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getsYear() {
        return sYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.S_YEAR
     *
     * @param sYear the value for TB_SKED.S_YEAR
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setsYear(BigDecimal sYear) {
        this.sYear = sYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.S_MONTH
     *
     * @return the value of TB_SKED.S_MONTH
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getsMonth() {
        return sMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.S_MONTH
     *
     * @param sMonth the value for TB_SKED.S_MONTH
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setsMonth(BigDecimal sMonth) {
        this.sMonth = sMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.S_DAY
     *
     * @return the value of TB_SKED.S_DAY
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getsDay() {
        return sDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.S_DAY
     *
     * @param sDay the value for TB_SKED.S_DAY
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setsDay(BigDecimal sDay) {
        this.sDay = sDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.P_ID
     *
     * @return the value of TB_SKED.P_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.P_ID
     *
     * @param pId the value for TB_SKED.P_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.PS_ID
     *
     * @return the value of TB_SKED.PS_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getPsId() {
        return psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.PS_ID
     *
     * @param psId the value for TB_SKED.PS_ID
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setPsId(BigDecimal psId) {
        this.psId = psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.S_STATE
     *
     * @return the value of TB_SKED.S_STATE
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public BigDecimal getsState() {
        return sState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.S_STATE
     *
     * @param sState the value for TB_SKED.S_STATE
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setsState(BigDecimal sState) {
        this.sState = sState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SKED.PS_NAME
     *
     * @return the value of TB_SKED.PS_NAME
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public String getPsName() {
        return psName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SKED.PS_NAME
     *
     * @param psName the value for TB_SKED.PS_NAME
     *
     * @mbg.generated Fri Feb 22 16:40:36 CST 2019
     */
    public void setPsName(String psName) {
        this.psName = psName == null ? null : psName.trim();
    }

    @Override
    public String toString() {
        return "Sked{" +
                "id=" + id +
                ", sYear=" + sYear +
                ", sMonth=" + sMonth +
                ", sDay=" + sDay +
                ", pId='" + pId + '\'' +
                ", psId=" + psId +
                ", sState=" + sState +
                ", psName='" + psName + '\'' +
                '}';
    }
}