package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Subtask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.S_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.S_SUMMARY
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private String sSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.P_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.U_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.U_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private BigDecimal uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUBTASK.S_STATE
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    private BigDecimal sState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.ID
     *
     * @return the value of TB_SUBTASK.ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.ID
     *
     * @param id the value for TB_SUBTASK.ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.S_NAME
     *
     * @return the value of TB_SUBTASK.S_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.S_NAME
     *
     * @param sName the value for TB_SUBTASK.S_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.S_SUMMARY
     *
     * @return the value of TB_SUBTASK.S_SUMMARY
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public String getsSummary() {
        return sSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.S_SUMMARY
     *
     * @param sSummary the value for TB_SUBTASK.S_SUMMARY
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setsSummary(String sSummary) {
        this.sSummary = sSummary == null ? null : sSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.P_ID
     *
     * @return the value of TB_SUBTASK.P_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.P_ID
     *
     * @param pId the value for TB_SUBTASK.P_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.U_NAME
     *
     * @return the value of TB_SUBTASK.U_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.U_NAME
     *
     * @param uName the value for TB_SUBTASK.U_NAME
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.U_ID
     *
     * @return the value of TB_SUBTASK.U_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public BigDecimal getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.U_ID
     *
     * @param uId the value for TB_SUBTASK.U_ID
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setuId(BigDecimal uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUBTASK.S_STATE
     *
     * @return the value of TB_SUBTASK.S_STATE
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public BigDecimal getsState() {
        return sState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUBTASK.S_STATE
     *
     * @param sState the value for TB_SUBTASK.S_STATE
     *
     * @mbg.generated Tue Dec 25 13:13:28 CST 2018
     */
    public void setsState(BigDecimal sState) {
        this.sState = sState;
    }

    @Override
    public String toString() {
        return "Subtask{" +
                "id=" + id +
                ", sName='" + sName + '\'' +
                ", sSummary='" + sSummary + '\'' +
                ", pId='" + pId + '\'' +
                ", uName='" + uName + '\'' +
                ", uId=" + uId +
                ", sState=" + sState +
                '}';
    }
}