package com.ztlt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ID
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.U_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.PWD
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ISSUBPACKAGE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private BigDecimal issubpackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.U_STATE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private BigDecimal uState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.U_TYPE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private BigDecimal uType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.U_TIME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private Date uTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.U_R_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    private String uRName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ID
     *
     * @return the value of TB_USER.ID
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ID
     *
     * @param id the value for TB_USER.ID
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.U_NAME
     *
     * @return the value of TB_USER.U_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.U_NAME
     *
     * @param uName the value for TB_USER.U_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.PWD
     *
     * @return the value of TB_USER.PWD
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.PWD
     *
     * @param pwd the value for TB_USER.PWD
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ISSUBPACKAGE
     *
     * @return the value of TB_USER.ISSUBPACKAGE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public BigDecimal getIssubpackage() {
        return issubpackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ISSUBPACKAGE
     *
     * @param issubpackage the value for TB_USER.ISSUBPACKAGE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setIssubpackage(BigDecimal issubpackage) {
        this.issubpackage = issubpackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.U_STATE
     *
     * @return the value of TB_USER.U_STATE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public BigDecimal getuState() {
        return uState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.U_STATE
     *
     * @param uState the value for TB_USER.U_STATE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setuState(BigDecimal uState) {
        this.uState = uState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.U_TYPE
     *
     * @return the value of TB_USER.U_TYPE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public BigDecimal getuType() {
        return uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.U_TYPE
     *
     * @param uType the value for TB_USER.U_TYPE
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setuType(BigDecimal uType) {
        this.uType = uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.U_TIME
     *
     * @return the value of TB_USER.U_TIME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.U_TIME
     *
     * @param uTime the value for TB_USER.U_TIME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.U_R_NAME
     *
     * @return the value of TB_USER.U_R_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public String getuRName() {
        return uRName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.U_R_NAME
     *
     * @param uRName the value for TB_USER.U_R_NAME
     *
     * @mbg.generated Fri Dec 21 10:10:22 CST 2018
     */
    public void setuRName(String uRName) {
        this.uRName = uRName == null ? null : uRName.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", uName='" + uName + '\'' +
                ", pwd='" + pwd + '\'' +
                ", issubpackage=" + issubpackage +
                ", uState=" + uState +
                ", uType=" + uType +
                ", uTime=" + uTime +
                ", uRName='" + uRName + '\'' +
                '}';
    }
}